In [2]:
import requests
from requests import ConnectionError,HTTPError,Timeout
url='https://data.ntpc.gov.tw/api/datasets/010E5B15-3823-4B20-B401-B1CF000550C5/json?page=0&size=2000'
try:
    response=requests.get(url)
    response.raise_for_status()
except ConnectionError:
    print('找不到伺服器')
except HTTPError:
    print('網頁找不到')
except Timeout:
    print('超過時間沒有回應')
else:
    print('沒有發生問題')

import pandas as pd
df1=pd.DataFrame(response.json(),
                columns=['sna','tot','sbi','sarea','ar','bemp'])
df2=df1.rename(columns={'sna':'站名','sarea':'區域','ar':'地址','tot':'數量','sbi':'可借','bemp':'可還'})

#小心資料類型
df2.info
df2

沒有發生問題

                        站名  數量  可借   區域                      地址  可還
0          YouBike2.0_下庄市場  20   1  八里區               舊城路21號(前)  19
1        YouBike2.0_八里行政中心  20   3  八里區    十三行路(靠中山路二段路口西南側人行道)  17
2    YouBike2.0_八里中庄市場綜合大樓  28  22  八里區    中山路一段268巷2號(對面汽車停車場)   6
3          YouBike2.0_大崁國小  20   9  八里區                忠八街2號(前)  11
4         YouBike2.0_龍形停車場  40  12  八里區        龍米路一段318號(對面停車場)  28
..                     ...  ..  ..  ...                     ...  ..
995        YouBike2.0_青潭國小  27   5  新店區                北宜路二段80號  22
996     YouBike2.0_中正路284巷  29  20  新店區           中正路284巷4弄3號南側   9
997      YouBike2.0_央北社會住宅  58  38  新店區        央北二路十四張口(西南側人行道)  20
998  YouBike2.0_中興路2段100巷口  21  11  新店區  五峰路63巷/中興路二段100巷口(天橋旁)  10
999      YouBike2.0_台北慈濟醫院  40  20  新店區              建國路289號旁空地  20

[1000 rows x 6 columns]

In [3]:
df2[['數量', '可還', '可借']]= df2[['數量', '可還', '可借']].astype(int)

In [4]:
df3 = df2[['區域', '數量', '可還', '可借']]
df3

      區域  數量  可還  可借
0    八里區  20  19   1
1    八里區  20  17   3
2    八里區  28   6  22
3    八里區  20  11   9
4    八里區  40  28  12
..   ...  ..  ..  ..
995  新店區  27  22   5
996  新店區  29   9  20
997  新店區  58  20  38
998  新店區  21  10  11
999  新店區  40  20  20

[1000 rows x 4 columns]

In [5]:
groupby = df3.groupby(by='區域')
groupby.sum()

       數量    可還    可借
區域
三峽區  1482   885   592
三芝區   153    44    61
三重區  3592  2204  1336
中和區  3381  2203  1146
五股區   566   359   201
八里區   443   274   161
土城區  2737  1864   836
坪林區    65     0     0
新店區  2031  1264   732
板橋區  6983  5042  1855
林口區  2073  1193   864
永和區  1545   983   536
汐止區  2353  1360   970
泰山區   557   390   163
淡水區  1909  1261   641
深坑區   122    90    32
瑞芳區   204    83    31
石碇區    29     0     0
石門區    82     0     0
萬里區    99    22     6
金山區   163    83    52